Repository LikeLion-at-DGU/2025-hackathon-5-jaego-backend, pull requests merged in 2025-08, with the labels that each got.

#3 [#2]feat: 앱 및 모델 설계
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests.py
  accounts/views.py
  categories/__init__.py
  categories/admin.py
  categories/apps.py
  categories/migrations/0001_initial.py
  categories/migrations/__init__.py
  categories/models.py
  categories/tests.py
  categories/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  project/settings.py
  reservations/__init__.py
  reservations/admin.py
  reservations/apps.py
  reservations/migrations/0001_initial.py
  reservations/migrations/__init__.py
  reservations/models.py
  reservations/tests.py
  reservations/views.py
Labels: ❤️ ready for review

#14 [#13] setting : Swagger 연동
  project/settings.py
  project/urls.py
  requirements.txt
Labels: ⚙ Setting, 🤍 연희

#17 [#16] main 앱 삭제, setting 수정, 프론트 배포 주소 수정, requirements.txt 업데이트
  main/__init__.py
  main/admin.py
  main/apps.py
  main/migrations/__init__.py
  main/models.py
  main/tests.py
  main/views.py
  project/settings.py
  requirements.txt
Labels: 📃 Docs, ❤️ merged

#19 [#11]feat: 상품 등록 로직 및 스키마 수정
  .gitignore
  accounts/permissions.py
  products/migrations/0005_product_image_alter_product_category_and_more.py
  products/models.py
  products/serializers.py
  products/urls.py
  products/views.py
  requirements.txt
  stores/migrations/0003_alter_store_seller.py
  stores/models.py
  stores/views.py
Labels: ✨ Feature, ⚙ Setting, 📬 API, 🤍 민정

#22 [#18] feat : 지도용 주변 상점 위치 API
  project/settings.py
  stores/views.py
Labels: ✨ Feature, 📬 API, 🤍 연희

#23 [#11] fix: 상품 등록, 수정할 때 discount_rate 자동 계산 및 저장
  products/serializers.py
  products/views.py
Labels: 🐞 BugFix, 📬 API, 🤍 연희, ❤️ merged

#33 [#26] fix : Delete etting : Swagger 연동
  etting : Swagger 연동
Labels: 🐞 BugFix, 🤍 연희

#35 [#26] fix : Delete .txt 업데이트
  .txt 업데이트
Labels: 🐞 BugFix, 🤍 연희

#36 [#26] fix: Delete celery.pid
  celery.pid
Labels: 🐞 BugFix, 🤍 연희

#37 [#26] fix : celery.py ignore 추가
  .gitignore
Labels: 🐞 BugFix, 🤍 연희

#38 [#25] reservations API 구현 및 테스트 완료
  reservations/models.py
  reservations/serializers.py
  reservations/tasks.py
  reservations/urls.py
  reservations/views.py
Labels: ✨ Feature, 📬 API, 🤍 연희

#42 [#11]feat: products 앱 내 기능 다수 구현
  accounts/permissions.py
  products/views.py
  requirements.txt
  reservations/migrations/0004_alter_reservation_status.py
Labels: ✨ Feature, ⚙ Setting, 📬 API, 🤍 민정, ❤️ ready for review

#44 [#11] products 앱 내 상품 상태 자동 변경 기능 구현
  .gitignore
  products/tasks.py
  project/settings.py
  requirements.txt
Labels: ✨ Feature, ⚙ Setting, 📬 API, 🤍 민정, ❤️ ready for review

#48 [#39] feat: 각 앱 별 admin,py 작성
  accounts/admin.py
  categories/admin.py
  products/admin.py
  reservations/admin.py
  stores/admin.py
Labels: ✨ Feature, 🤍 연희, ❤️ merged

#49 [#40] fix : store api 권한 재설정
  stores/views.py
Labels: 🐞 BugFix, 🤍 연희, ❤️ merged

#53 [#39] deploy : 파일 업로드 제한 200MB
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희, ❤️ merged

#58 [#55] fix : log 가독성 강화
  reservations/tasks.py
Labels: 🐞 BugFix, 🤍 연희

#61 [#45] docs: requirements.txt 변경
  requirements.txt
Labels: 🐞 BugFix, 📃 Docs

#62 [#45] fix : import 경로 수정 및 requirements 업데이트
  accounts/services/recommend.py
  requirements.txt
Labels: 🐞 BugFix, 🤍 연희

#67 [#66] deploy : 프론트 서버 주소 입력
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희

#68 [#66] deploy: 프론트 로컬 링크 추가
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희

#69 [#66] deploy: 프론트 로컬 링크 수정
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희

#70 [#66] deploy: 프론트 링크 수정
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희

#72 [#71] fix : StoreStep2 API serializers 재설정
  stores/views.py
Labels: 🐞 BugFix, 🤍 연희

#75 [#8] refac : store 모델 str 수정
  stores/models.py
Labels: 🔨 Refactor, 🤍 연희

#78 [#77] Fix: 비활성화된 상품 찜 목록에서 제거
  products/apps.py
  products/signals.py
  project/settings.py
Labels: 🐞 BugFix, 🤍 민정, ❤️ merged, 🖤 done

#80 [#79] feat : 취소 요청 시 취소 사유 입력, 예약 목록 조회 시 cancel_reason 필드 추가
  reservations/models.py
  reservations/serializers.py
  reservations/views.py
Labels: ✨ Feature, 📬 API, 🤍 연희

#83 [#81] docs : install app 정리
  project/settings.py
Labels: 📃 Docs, 🤍 연희

#86 [#85] feat : ready status 추가 및 관련 API 추가
  reservations/models.py
  reservations/serializers.py
  reservations/views.py
Labels: 📬 API, 🤍 연희

#88 [#87] refac : 근처 가게 상품 목록 조회 API 로직 수정
  products/views.py
Labels: 📬 API, 🤍 연희

#90 [#89]fix: 예약 목록 조회 시 가게 위치 반환
  reservations/serializers.py
Labels: enhancement, 📬 API, 🤍 민정

#91 [#84] feat : 추천 ai 로직 embedding 방식으로 변경
  .gitignore
  accounts/services/recommend.py
  accounts/urls.py
  accounts/views.py
  products/views.py
  project/settings.py
Labels: ✨ Feature, 📬 API, 🤍 연희

#93 [#84] docs : requirements.txt 수정
  requirements.txt
Labels: 📃 Docs, 🤍 연희

#100 [#99]Fix: 상품 목록 조회 시 위도경도 반환 추가
  products/serializers.py
Labels: 📬 API, 🤍 민정

#102 [#95] fix : 오타 수정
  products/views.py
Labels: 🐞 BugFix, 📬 API, 🤍 연희

#105 [#95] fix : 찜이 없으면 추천 상품 안 뜨게 수정
  accounts/services/reco.py
Labels: 🐞 BugFix, 🤍 연희

#106 [#95] fix : ProductRead 시리얼라이저 store_name 필드 추가
  products/serializers.py
Labels: 🐞 BugFix, 🤍 연희

#107 [#95] fix : reservation 예약 조회 시 product 관련 정보 추가
  reservations/serializers.py
Labels: 🐞 BugFix, 🤍 연희

#110 [#94] deploy : 재고 업데이트 시 임베딩 데이터 주기적 업데이트 + 오전/오후 3시 자동 임베딩 업데이트
  products/management/commands/build_embeddings.py
  products/signals.py
  products/tasks.py
  project/settings.py
  reservations/serializers.py
Labels: 🌏 Deploy, 🤍 연희

#112 [#95] refac : reservation read serializer 수정
  reservations/serializers.py
Labels: 🔨 Refactor, 🤍 연희

#134 [#94] deploy : 추천 상품 임베딩 스케줄 한시간에 한 번으로 수정
  project/settings.py
Labels: 🌏 Deploy, 🤍 연희

#136 [#95] accounts, categories 앱 리팩토링
  accounts/apps.py
  accounts/models.py
  accounts/permissions.py
  accounts/serializers.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  categories/apps.py
  categories/serializers.py
  categories/tests.py
  categories/urls.py
  categories/views.py
Labels: 🔨 Refactor, 🤍 민정

#137 [#94] refac : 추천 상품 AI 로직에 거리 점수 + 5km 제한 + 필터 추가
  accounts/services/reco.py
  accounts/views.py
Labels: 🔨 Refactor, 🤍 연희

#138 [#94] refac : 추천 키워드 가중치 수정
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#140 [#94] refac : 추천 점수 로그 추가
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#145 [#95] 리팩토링
  products/apps.py
  products/serializers.py
  products/signals.py
  products/tasks.py
  products/tests.py
  products/views.py
  project/celery.py
  reservations/admin.py
  reservations/apps.py
  reservations/serializers.py
  reservations/tasks.py
  reservations/tests.py
  reservations/views.py
  stores/admin.py
  stores/apps.py
  stores/models.py
  stores/serializers.py
  stores/tests.py
  stores/utils/geocode.py
  stores/views.py
Labels: 🐞 BugFix, 🔨 Refactor, 🤍 민정

#146 [#94] refac : 로그 기능 수정
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#148 [#94] refac : 가중치 총 합 수정2
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#149 [#94] refac : 가중치 총 합 수정 3
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#151 [#94] refac : 가중치 총 합 수정 7
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#153 [#94] refac : 가중치 총 합 수정 9
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#155 [#94] refac : 가중치 총 합 수정 10
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#156 [#94] refac : 가중치 총 합 수정 11
  accounts/services/reco.py
Labels: 🔨 Refactor, 🤍 연희

#158 [#94] refac : 가중치 총 합 수정 12
  accounts/services/reco.py
  accounts/services/recommend.py
Labels: 🔨 Refactor, 🤍 연희
